# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'features.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QTextEdit
from extraction import extractflow1, extractflow2, extracinformation, extracinformation_1, extracinformation_2, \
    extracinformation_3

pro, srcip, dstip, sport, dport = extracinformation(extractflow1)
min_data_ip, q1_data_ip, med_data_ip, mean_data_ip, q3_data_ip, max_data_ip, var_data_ip, min_data_wire, q1_data_wire, med_data_wire, mean_data_wire, q3_data_wire, max_data_wire, var_data_wire = extracinformation_1(
    extractflow1)
min_data_control, q1_data_control, med_data_control, mean_data_control, q3_data_control, max_data_control, var_data_control, total_packets, ack_pkts_sent, pure_acks_sent, actual_data_bytes, pushed_data_pkts, SYN_pkts_sent, FIN_pkts_sent, urgent_data_pkts = extracinformation_2(
    extractflow1)
max_win_adv, min_win_adv, zero_win_adv, avg_win_adv, flowlen = extracinformation_3(extractflow1)


# print(flowlen)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(701, 548)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 50, 201, 41))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(260, 60, 141, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.setPlaceholderText("——请选择——")
        self.comboBox.currentIndexChanged.connect(self.selectionchange)

        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(180, 100, 101, 41))
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 110, 161, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(290, 110, 101, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 160, 361, 41))
        self.label_4.setObjectName("label_4")

        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(350, 160, 181, 41))
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(560, 160, 91, 41))
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(70, 240, 101, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(70, 280, 101, 31))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(70, 330, 101, 31))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(70, 390, 101, 31))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(70, 430, 101, 31))
        self.label_9.setObjectName("label_9")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(170, 230, 181, 41))
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(170, 280, 181, 41))
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_5.setGeometry(QtCore.QRect(170, 330, 181, 41))
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit_6 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_6.setGeometry(QtCore.QRect(170, 380, 181, 41))
        self.textEdit_6.setObjectName("textEdit_6")
        self.textEdit_7 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_7.setGeometry(QtCore.QRect(170, 430, 181, 41))
        self.textEdit_7.setObjectName("textEdit_7")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(440, 230, 91, 31))
        self.label_10.setObjectName("label_10")
        self.textEdit_8 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_8.setGeometry(QtCore.QRect(440, 270, 191, 201))
        self.textEdit_8.setObjectName("textEdit_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 701, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.pushButton.clicked.connect(self.pushButton_click)
        self.textEdit_2.textChanged.connect(self.textEdit_2_change)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "请选择要解析的pacp文件："))
        self.comboBox.setItemText(0, _translate("MainWindow", "jingdong.pcap"))
        self.comboBox.setItemText(1, _translate("MainWindow", "doubai.pcap"))
        self.label_2.setText(_translate("MainWindow", "该文件夹下共有"))
        self.label_3.setText(_translate("MainWindow", "个数据流"))
        self.label_4.setText(_translate("MainWindow", "请输入提取流的编号（1--数据流总数）："))
        self.pushButton.setText(_translate("MainWindow", "提取"))
        self.label_5.setText(_translate("MainWindow", "protocol:"))
        self.label_6.setText(_translate("MainWindow", "src ip:"))
        self.label_7.setText(_translate("MainWindow", "dst ip:"))
        self.label_8.setText(_translate("MainWindow", "src port:"))
        self.label_9.setText(_translate("MainWindow", "dst port:"))
        self.label_10.setText(_translate("MainWindow", "其他信息："))

    def selectionchange(self, i):
        global m, flowlen
        m = i
        if m == 0:
            flowlen = extracinformation_3(extractflow1)[4]
            self.textEdit.setText(str(flowlen))

        if m == 1:
            flowlen = extracinformation_3(extractflow2)[4]
            self.textEdit.setText(str(flowlen))
        return m, flowlen

    def pushButton_click(self):
        # m, flowlen = self.selectionchange()
        if isnum(str1)==True and 0 < int(str1) <= flowlen:
            str2 = int(str1)
            # print(str2)
            # print(type(str2))
            # print(m)
            # pro = extracinformation(extractflow1)[0][str2 - 1]
            # print(pro)
            if m==0:
                pro = extracinformation(extractflow1)[0][str2-1]
                srcip = extracinformation(extractflow1)[1][str2-1]
                dstip = extracinformation(extractflow1)[2][str2-1]
                sport = extracinformation(extractflow1)[3][str2-1]
                dport = extracinformation(extractflow1)[4][str2-1]
                mean_data_ip = extracinformation_1(extractflow1)[3][str2-1]
                total_packets =  extracinformation_2(extractflow1)[7][str2-1]
                max_win_adv = extracinformation_3(extractflow1)[0][str2-1]

                self.textEdit_3.setText(pro)
                self.textEdit_4.setText(srcip)
                self.textEdit_5.setText(dstip)
                self.textEdit_6.setText(str(sport))
                self.textEdit_7.setText(str(dport))
                self.textEdit_8.setText("该流ip数据包平均长度："+str(mean_data_ip)+"\n"+"该流的数据包总数："+str(total_packets)+"\n"+"该流的最大窗口数:"+str(max_win_adv))
            if m ==1:
                pro = extracinformation(extractflow2)[0][str2-1]
                srcip = extracinformation(extractflow2)[1][str2-1]
                dstip = extracinformation(extractflow2)[2][str2-1]
                sport = extracinformation(extractflow2)[3][str2-1]
                dport = extracinformation(extractflow2)[4][str2-1]
                mean_data_ip = extracinformation_1(extractflow1)[3][str2-1]
                total_packets =  extracinformation_2(extractflow1)[7][str2-1]
                max_win_adv = extracinformation_3(extractflow1)[0][str2-1]
                self.textEdit_3.setText(pro)
                self.textEdit_4.setText(srcip)
                self.textEdit_5.setText(dstip)
                self.textEdit_6.setText(str(sport))
                self.textEdit_7.setText(str(dport))
                self.textEdit_8.setText("该流ip数据包平均长度："+str(mean_data_ip)+"\n"+"该流的数据包总数："+str(total_packets)+"\n"+"该流的最大窗口数:"+str(max_win_adv))
        else:
            print("输入有误，请重新输入")


    def textEdit_2_change(self):
        global str1
        str1 = self.textEdit_2.toPlainText()
        return str1


def isnum(s):
    for i in s:
        if i.isdigit():
            continue
        else:
            return False
    return True


